AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: fedsample API

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    Environment:
      Variables:
        STAGE: !Ref Stage

  HttpApi:
    CorsConfiguration:
      AllowOrigins:
        - "*"
      AllowMethods:
        - GET
        - POST
        - OPTIONS
      AllowHeaders:
        - Content-Type
        - Authorization

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]

Resources:

  SearchMembersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-searchMembers"
      CodeUri: searchMembers/
      Handler: index.handler
      Description: Search member DB and return list
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /members/search
            Method: GET

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
